### ISSUE TITLE
Stay on top of commits to Drupal 7 project

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/project#47]
There have been several releases of the Drupal 7 project module since this version was forked. We should see if we want any of those commits on this project.

Git tag 7.x-2.0-alpha1

* [ ] | [#985994](https://www.drupal.org/node/985994) Invoke a hook when project release XML has been written
* [ ] | [#2479625](https://www.drupal.org/node/2479625) by aaronbauman, Pere Orga: Add taxonomy dependency to project releases

Git tag 7.x-2.0-alpha2

* [x] | N/A [#2600432](https://www.drupal.org/node/2600432) Add UPGRADE.txt
* [ ] | [#1925728](https://www.drupal.org/node/1925728) Schema inconsistent: several columns difference on "not null"

Git tag 7.x-2.0-alpha3

* [ ] | [#2163051](https://www.drupal.org/node/2163051) Cannot create releases
* [ ] | [#2615184](https://www.drupal.org/node/2615184) Update project_release_files view, add content pane display

See also: 
* https://github.com/backdrop-contrib/project/issues/45
* https://github.com/backdrop-contrib/project/issues/46
